repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"
      - id: terraform-validate
      #- id: terraform-fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      # - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=.tfdocs-config.yml
      - id: terraform_fmt
    #  - id: terraform_tflint
    #  - id: checkov
    #    args: [--soft-fail]
      - id: terraform_checkov
        args:
          - --args=--quiet

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.15.0
    hooks:
      - id: check-github-workflows

  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.8.4
  #   hooks:
  #   - id: gitleaks

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']

  # - repo: https://github.com/jackdewinter/pymarkdown
  #   rev: v0.9.5
  #   hooks:
  #     - id: pymarkdown
  #       name: PyMarkdown
  #       description: "PyMarkdown"
  #       files: ^.*.md$
  #       entry: pymarkdown
  #       # args:
  #       #   - --config=clean.json
  #       #   - scan