name: caller-workflow
on:
  pull_request:
  push:
    branches:
      - master
# 2
jobs:
  call-the-workflow:
    uses: action-foobar/action-testing/.github/workflows/caller-workflow.yml@master
    with:
      TRIGGER_EVENT : ${{ github.event_name }}
