name: called worfklow test

env:
  TRIGGER_EVENT: ${{ inputs.TRIGGER_EVENT }}

on:
  workflow_call:
    inputs:
      TRIGGER_EVENT:
        required: true
        type: string
      ENV_SECRET_ARRAY:
        description: test
        required: false
        type: string
        
jobs:
#   run_on_push:
#     name: push
#     runs-on: ubuntu-latest
#     if: ${{ inputs.TRIGGER_EVENT == 'push' }}
#     steps:
#       - name: print
#         run:  |
#           echo ${{ inputs.TRIGGER_EVENT }}
#           echo "push workflow"
#           echo ${{ inputs.ENV_SECRET_ARRAY }}

  run_on_pullrequest:
    name: pr
    runs-on: ubuntu-latest
   # if: ${{ inputs.TRIGGER_EVENT == 'pull_request' }}
    steps:
      - name: print
        run:  |
          echo ${{ inputs.TRIGGER_EVENT }} 
          echo "pull request workflow"
          echo ${{ fromJson(inputs.ENV_SECRET_ARRAY) }}
          echo ::set-output name=list::${{ fromJson(inputs.ENV_SECRET_ARRAY) }}


  job2:
    needs: ["run_on_pullrequest"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ needs.run_on_pullrequest.outputs.list }}
    steps:
      - run: |
          echo "🎉 The job was automatically triggered by an event."
          echo ${{ matrix.node }}
