name: Request JWT from GitHub OIDC Provider
on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  get-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request JWT from GitHub OIDC Provider
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)

      - name: Print JWT
        run: echo ${{ steps.idtoken.outputs.id_token }}