name: pr-type-test

env:
  GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "something"
          echo ${{ env.GITHUB_CONTEXT }}
          #echo ${{ toJson(github.event) }}
